name: Build and test

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        conf-ssl: [--without-ssl]
    steps:
    - uses: actions/checkout@v2
    - run: ./autogen.sh
    - run: case ${{matrix.conf-ssl}} in
           *gnutls) sudo apt-get update && sudo apt-get -y install libgnutls28-dev gnutls-bin xmlto ;;
           esac
    - run: ./configure ${{matrix.conf-ssl}} --prefi $HOME/inst 
    - run: make
    - run: make check
    - run: make install
